## Convert Pressure to Cp

In [14]:
import pandas as pd
import numpy as np

In [15]:
csv_pressure = "CAARC_example_CAARC_015/000/probes/hist_series/body_Pressure_body/bodies.body_Pressure_body.pressure.csv"
csv_atm = "CAARC_example_CAARC_015/000/probes/hist_series/point_Pressure_probe/points.point_Pressure_probe.pressure.csv"
Uh_ms = 70
rho_inf = 1.225

csv_cp_out = "CAARC_example_CAARC_015/000/probes/hist_series/body_Pressure_body/bodies.body_Pressure_body.cp.csv"

In [16]:
df_pressure = pd.read_csv(csv_pressure)
df_pressure

,time_step,0,1,2,3,4,5,6,7,8,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,0.000000,0.0000,0.0000,0.00000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.00000,0.00000,0.00000,0.000000,0.00000,0.0000,0.00000,0.000000
1,0.032995,5042.8280,-2351.6094,305.24220,2507.1719,4592.3047,2814.5938,-4787.4375,-2431.3438,-4779.7580,...,-2332.2110,-2728.3516,-139.73438,-641.17970,274.16406,93.484375,67.25781,-663.5156,-390.17970,-146.710940
2,0.065990,4820.2500,-2197.1875,456.46094,1893.6406,3022.3750,2511.1406,-4687.1330,-2021.5938,-3464.4766,...,-2207.7656,-2306.0938,-227.64844,-218.47656,277.28906,-264.203120,-305.39062,-679.6406,-48.81250,-20.898438
3,0.098985,3622.9922,-2387.3516,357.16406,1576.9766,2772.5312,2369.9297,-2895.6094,-2131.1953,-2940.3516,...,-2424.5234,-2225.3750,-338.48438,-235.42188,807.03906,239.804690,-690.08594,-530.5547,-364.57030,-426.125000
4,0.131980,2829.9844,-3870.7266,640.67190,2136.0625,3414.1953,2992.7969,-2716.2656,-2849.0860,-3581.2110,...,-3900.0547,-3300.8203,475.28125,964.50780,284.37500,143.812500,-663.52344,-1030.0234,429.16406,583.242200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,32.862965,6661.7970,5363.4453,5421.63300,6202.2344,6744.7266,6323.0390,5574.7344,5641.4062,5500.2500,...,5483.0000,5478.6170,5650.95300,5658.67200,5427.80470,5426.039000,5435.82800,5437.2030,5647.38300,5639.343800
997,32.895958,6660.0156,5361.2580,5420.34380,6202.9140,6746.2420,6318.9297,5577.7890,5644.2266,5503.3516,...,5485.7030,5481.9140,5647.53900,5656.81250,5427.80470,5426.554700,5435.06250,5438.4140,5645.12500,5637.484400
998,32.928955,6662.2656,5357.5390,5419.92970,6197.8750,6744.7890,6319.1484,5582.5390,5642.5938,5498.9530,...,5478.2812,5476.2812,5645.76560,5653.03900,5426.79700,5426.179700,5434.93750,5438.1170,5644.87500,5638.226600
999,32.961950,6657.9844,5359.4220,5421.63300,6198.8516,6738.2580,6321.5860,5580.8125,5645.0547,5495.5547,...,5478.3280,5474.8125,5645.41400,5654.46880,5428.28900,5426.429700,5431.84380,5436.9375,5644.10940,5636.804700
1000,32.994946,6657.8516,5359.9375,5420.94530,6198.2188,6740.3984,6318.8670,5582.2030,5645.3438,5498.3280,...,5479.6094,5478.0703,5639.53120,5648.93750,5427.82030,5426.554700,5429.87500,5434.4297,5639.38300,5633.258000

In [17]:
df_atm = pd.read_csv(csv_atm)
df_atm

      time_step            0
0      0.000000     0.000000
1      0.032995     0.000000
2      0.065990     0.000000
3      0.098985     0.000000
4      0.131980    -0.007812
...         ...          ...
996   32.862965  6018.289000
997   32.895958  6018.922000
998   32.928955  6018.304700
999   32.961950  6016.758000
1000  32.994946  6016.297000

[1001 rows x 2 columns]

In [18]:
# Add atm column
df_pressure["atm"] = df_atm["0"]
df_pressure

,time_step,0,1,2,3,4,5,6,7,8,...,1991,1992,1993,1994,1995,1996,1997,1998,1999,atm
0,0.000000,0.0000,0.0000,0.00000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.00000,0.00000,0.00000,0.000000,0.00000,0.0000,0.00000,0.000000,0.000000
1,0.032995,5042.8280,-2351.6094,305.24220,2507.1719,4592.3047,2814.5938,-4787.4375,-2431.3438,-4779.7580,...,-2728.3516,-139.73438,-641.17970,274.16406,93.484375,67.25781,-663.5156,-390.17970,-146.710940,0.000000
2,0.065990,4820.2500,-2197.1875,456.46094,1893.6406,3022.3750,2511.1406,-4687.1330,-2021.5938,-3464.4766,...,-2306.0938,-227.64844,-218.47656,277.28906,-264.203120,-305.39062,-679.6406,-48.81250,-20.898438,0.000000
3,0.098985,3622.9922,-2387.3516,357.16406,1576.9766,2772.5312,2369.9297,-2895.6094,-2131.1953,-2940.3516,...,-2225.3750,-338.48438,-235.42188,807.03906,239.804690,-690.08594,-530.5547,-364.57030,-426.125000,0.000000
4,0.131980,2829.9844,-3870.7266,640.67190,2136.0625,3414.1953,2992.7969,-2716.2656,-2849.0860,-3581.2110,...,-3300.8203,475.28125,964.50780,284.37500,143.812500,-663.52344,-1030.0234,429.16406,583.242200,-0.007812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,32.862965,6661.7970,5363.4453,5421.63300,6202.2344,6744.7266,6323.0390,5574.7344,5641.4062,5500.2500,...,5478.6170,5650.95300,5658.67200,5427.80470,5426.039000,5435.82800,5437.2030,5647.38300,5639.343800,6018.289000
997,32.895958,6660.0156,5361.2580,5420.34380,6202.9140,6746.2420,6318.9297,5577.7890,5644.2266,5503.3516,...,5481.9140,5647.53900,5656.81250,5427.80470,5426.554700,5435.06250,5438.4140,5645.12500,5637.484400,6018.922000
998,32.928955,6662.2656,5357.5390,5419.92970,6197.8750,6744.7890,6319.1484,5582.5390,5642.5938,5498.9530,...,5476.2812,5645.76560,5653.03900,5426.79700,5426.179700,5434.93750,5438.1170,5644.87500,5638.226600,6018.304700
999,32.961950,6657.9844,5359.4220,5421.63300,6198.8516,6738.2580,6321.5860,5580.8125,5645.0547,5495.5547,...,5474.8125,5645.41400,5654.46880,5428.28900,5426.429700,5431.84380,5436.9375,5644.10940,5636.804700,6016.758000
1000,32.994946,6657.8516,5359.9375,5420.94530,6198.2188,6740.3984,6318.8670,5582.2030,5645.3438,5498.3280,...,5478.0703,5639.53120,5648.93750,5427.82030,5426.554700,5429.87500,5434.4297,5639.38300,5633.258000,6016.297000

In [19]:
column_pts = [c for c in df_pressure.columns if c.isnumeric()]
len(column_pts)

2000

In [20]:
df_pressure[column_pts] = (df_pressure[column_pts].to_numpy().T - df_pressure["atm"].to_numpy()).T / (0.5 * rho_inf * (Uh_ms ** 2))
df_pressure[column_pts]

,0,1,2,3,4,5,6,7,8,9,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1.680243,-0.783543,0.101705,0.835376,1.530131,0.937807,-1.595148,-0.810110,-1.592589,-1.619752,...,-0.777080,-0.909072,-0.046559,-0.213638,0.091350,0.031148,0.022410,-0.221080,-0.130006,-0.048883
2,1.606081,-0.732091,0.152090,0.630951,1.007039,0.836698,-1.561727,-0.673584,-1.154345,-1.161331,...,-0.735615,-0.768378,-0.075851,-0.072795,0.092391,-0.088031,-0.101754,-0.226453,-0.016264,-0.006963
3,1.207161,-0.795452,0.119005,0.525440,0.923792,0.789648,-0.964801,-0.710103,-0.979709,-0.988455,...,-0.807838,-0.741483,-0.112781,-0.078441,0.268901,0.079902,-0.229933,-0.176778,-0.121473,-0.141983
4,0.942938,-1.289702,0.213471,0.711727,1.137594,0.997186,-0.905042,-0.949297,-1.193237,-1.192373,...,-1.299474,-1.099813,0.158364,0.321371,0.094755,0.047920,-0.221080,-0.343196,0.142998,0.194336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,0.214413,-0.218190,-0.198802,0.061290,0.242045,0.101541,-0.147790,-0.125575,-0.172608,-0.167066,...,-0.178355,-0.179816,-0.122394,-0.119822,-0.196746,-0.197334,-0.194073,-0.193615,-0.123584,-0.126262
997,0.213609,-0.219130,-0.199443,0.061305,0.242339,0.099961,-0.146983,-0.124846,-0.171785,-0.167024,...,-0.177666,-0.178928,-0.123743,-0.120653,-0.196957,-0.197374,-0.194539,-0.193422,-0.124547,-0.127093
998,0.214564,-0.220163,-0.199375,0.059832,0.242061,0.100239,-0.145195,-0.125185,-0.173045,-0.166649,...,-0.179933,-0.180599,-0.124128,-0.121705,-0.197087,-0.197293,-0.194375,-0.193315,-0.124425,-0.126640
999,0.213653,-0.219021,-0.198292,0.060673,0.240400,0.101567,-0.145255,-0.123849,-0.173662,-0.167334,...,-0.179402,-0.180573,-0.123730,-0.120713,-0.196075,-0.196694,-0.194890,-0.193193,-0.124164,-0.126598
1000,0.213762,-0.218695,-0.198368,0.060615,0.241267,0.100815,-0.144638,-0.123600,-0.172584,-0.166871,...,-0.178821,-0.179334,-0.125536,-0.122402,-0.196077,-0.196499,-0.195393,-0.193875,-0.125586,-0.127626

In [22]:
df_pressure.to_csv(csv_cp_out, index=None)